const content = {
  en: {
    privacy: {
      heading: "Privacy Policy",
      subheading: "We value your privacy",
      link: "Privacy Policy",
      consent: "I have read and agree to the ",
      title: "Privacy Policy for NEROM Engineering Business & Services",
      lastUpdated: "Last Updated: 11.03.2025",
      intro:
        "At NEROM Engineering Business & Services, we respect your privacy and are committed to protecting the personal data you share with us. This privacy policy explains how we collect, use, and protect your personal data, particularly through the use of Google Analytics.",
      information: {
        title: "1. Information We Collect",
        content:
          "Currently, we do not collect personal information directly from visitors to our website, aside from data collected through Google Analytics and the email and message collected from the contact form.",
      },
      googleAnalytics: {
        title: "2. Use of Google Analytics",
        content:
          "We use Google Analytics, a web analytics service provided by Google, Inc. Google Analytics uses cookies to help us understand how visitors interact with our website. The information generated by these cookies about your use of the website (including your anonymized IP address) is transmitted to and stored by Google on servers in the United States.",
        second:
          "We have implemented IP anonymization in Google Analytics to ensure that the last part of your IP address is not collected and stored.",
      },
      cookies: {
        title: "3. Cookies",
        content:
          "Our website uses cookies to improve your experience while navigating through our content. Cookies are small text files that are stored on your device and help us understand how you interact with our website. You can disable cookies in your browser settings, but this may affect your experience on our website.",
      },
      dataRetention: {
        title: "4. Data Retention",
        content:
          "We retain personal data collected through Google Analytics and the contact form for a period of 26 months. After this period, the data is automatically deleted.",
      },
      rights: {
        title: "5. Your Rights",
        content:
          "You have the right to access, update, or delete your personal data collected through Google Analytics and the contact form. If you wish to exercise these rights, please contact us at ",
      },
      internationalDataTransfers: {
        title: "6. International Data Transfers",
        content:
          "Please note that data collected by Google Analytics may be transferred to servers located in the United States, which may have different data protection laws than those in the EU. By using our website, you consent to the transfer of your data outside the EU, subject to the safeguards in place, such as Google’s use of Standard Contractual Clauses for international data transfers.",
      },
      thirdPartyServices: {
        title: "7. Third-Party Services",
        content:
          "We do not share any personal data with third-party services outside of Google Analytics. However, if we decide to work with other third-party services in the future, we will update this privacy policy accordingly.",
      },
      changes: {
        title: "8. Changes to This Policy",
        content:
          "We reserve the right to update this privacy policy to reflect changes in our practices or legal requirements. We encourage you to review this page regularly for the latest information on our privacy practices.",
      },
      contact: {
        title: "9. Contact Us",
        content:
          "If you have any questions about this privacy policy or how we handle your personal data, please contact us at:",
      },
    },
    navigation: {
      lang: "Language",
      home: "Home",
      services: "Services",
      contact: "Contact",
    },
    hero: {
      title: "NEROM",
      description: "Engineering & Business Services",
    },
    whoWeAre: {
      title: "Who we are",
      first:
        "Welcome to NEROM Engineering Business & Services, a specialized provider of technical and consulting services. With expertise in engineering, business strategy, and executive training, we offer comprehensive solutions tailored to meet the modern market's demands.",
      second:
        "From technical studies and engineering consulting to business advisory and specialized training, NEROM combines expertise with innovation, ensuring high-quality services that drive growth and success for our clients.",
      third: "Discover how we can help you achieve your goals.",
    },
    expertise: {
      title: "Our expertise",
      learnMore: "Learn more",
      engineering: {
        title: "Engineering",
        description:
          "NEROM Engineering Business & Services brings extensive experience in engineering, offering specialized services in design, studies, and technical consulting. With deep expertise in architectural, mechanical, software and chemical projects, we support businesses and professionals with innovative and efficient solutions, ensuring quality, precision, and compliance with the highest standards.",
      },
      business: {
        title: "Business",
        description:
          "At NEROM Engineering Business & Services, we have extensive experience in business consulting, helping companies develop effective strategies and optimize their operations. We offer specialized services in marketing, sales promotion, and executive training, providing practical and innovative solutions that drive growth and competitiveness.",
      },
    },
    services: {
      hero: {
        title: "Services",
        description: "We offer a wide range of services",
      },
      engineering: {
        title: "Engineering",
        description:
          "At NEROM Engineering Business & Services, we offer a wide range of engineering services, providing technical expertise and innovative solutions for every project. Our experience spans studies, design, and technical consulting, ensuring quality, precision, and compliance with the highest standards.",
        listTitle: "Our services include:",
        first:
          "Technical studies and consulting services for architectural, mechanical, software and chemical projects",
        second: "Project support from initial conception to implementation",
        third: "Specialized technical consulting in engineering and design",
        fourth:
          "Development of innovative solutions for industrial and technical applications",
        secondListTitle: "Engineering segments:",
        secondList: {
          first: "Space and small space design and construction",
          second: "Solution/Article design",
          third: "Energy design and engineering",
          fourth: "Chemical process engineering",
          fifth: "Software solutions and website design (like this one)",
        },
        actionLabel: "Learn more about architecture",
      },
      business: {
        title: "Business",
        description:
          "NEROM Engineering Business & Services offers specialized business consulting services, helping companies optimize their strategy, enhance their competitiveness, and achieve sustainable growth. Through targeted solutions and practical advice, we support businesses of all sizes to adapt to the modern market's demands.",
        listTitle: "Our services include:",
        first:
          "Strategic consulting services for business development and optimization",
        second:
          "Marketing and sales promotion advice for increased efficiency and brand awareness",
        third:
          "Training and development of executives through specialized seminars and educational programs",
        fourth:
          "Market and competition analysis, helping businesses make informed decisions",
        secondListTitle: "Business segments:",
        secondList: {
          first: "Product and business development",
          second: "Operational strategies",
          third: "Marketing campains",
          fourth: "Training of commercial effectiveness",
        },
      },
      other: {
        title: "Other services",
        description:
          "In addition to the above services, NEROM Engineering Business & Services offers additional specialized services that complement and enhance our activities. Our goal is to provide comprehensive solutions that meet the needs of our partners with professionalism and expertise.",
        listTitle: "Our services include:",
        first:
          "Educational seminars and training, aimed at developing skills and professional training",
        second:
          "Production of original recordings, covering specialized needs in sound and multimedia",
        third:
          "Specialized professional services, tailored to the requirements of each client",
      },
    },
    contact: {
      hero: {
        title: "Contact us",
        description: "Happy customers are our first priority",
      },
      title: "Where to find us",
      content:
        "Get in touch with us to learn more about our services or discuss your project and business needs. You can call us, send us an email, or use our contact form.",
      contactDetails: "Contact details",
      address: "188 Ipokratous Str., Athens 11471",
      contactForm: "Contact form",
      subject: {
        label: "Subject",
        options: {
          general: "General inquiry",
          engineering: "Engineering services",
          business: "Business consulting",
          other: "Other services",
        },
        hint: "Please choose a value",
      },
      email: {
        label: "Email",
        hint: "Please enter a valid email address",
      },
      message: {
        label: "Message",
        hint: "Only letters, numbers, spaces, and punctuation are allowed",
      },
      send: "Send",
      success: {
        title: "Message sent",
        content:
          "Thank you for contacting us. We will get back to you as soon as possible.",
        actionButtonLabel: "Back to contact",
      },
      error: {
        title: "Error",
        content:
          "An error occurred while sending your message. Please try again later.",
        actionButtonLabel: "Back to contact",
      },
    },
    architecture: {
      title: "Architecture",
      description: "Our architectural services are tailored to meet your needs",
      back: "Back to architecture",
      projects: {
        filiates: {
          title: "Cozy Small House in Filiates",
          description:
            "A cozy small house located in the picturesque village of Filiates, offering a peaceful retreat in the heart of nature. The house features a traditional design with modern amenities, providing a comfortable and relaxing environment for its residents.",
          alt1: "Modern Bathroom",
          alt2: "Spacious Kitchen",
          alt3: "Kitchen with Side Table",
        },
        lux_home: {
          title: "Elegant Luxury House",
          description:
            "An elegant luxury house designed to offer the ultimate in comfort and style. The house features spacious rooms, modern amenities, and luxurious finishes, creating a sophisticated and welcoming environment for its residents.",
          alt1: "Modern Kitchen",
          alt2: "Children's Room",
          alt3: "Master Bedroom",
          alt4: "Bedroom and Walk-in Closet",
          alt5: "Walk-in Closet",
        },
      },
    },
  },
  el: {
    privacy: {
      heading: "Πολιτική Απορρήτου",
      subheading: "Σεβόμαστε την ιδιωτικότητά σας",
      link: "Πολιτική Απορρήτου",
      consent: "Έχω διαβάσει και συμφωνώ με την ",
      title: "Πολιτική Απορρήτου για την NEROM Engineering Business & Services",
      lastUpdated: "Τελευταία ενημέρωση: 11.03.2025",
      intro:
        "Στην NEROM Engineering Business & Services, σεβόμαστε την ιδιωτικότητά σας και δεσμευόμαστε να προστατεύουμε τα προσωπικά δεδομένα που μοιράζεστε μαζί μας. Αυτή η πολιτική απορρήτου εξηγεί πώς συλλέγουμε, χρησιμοποιούμε και προστατεύουμε τα προσωπικά σας δεδομένα, ιδιαίτερα μέσω της χρήσης του Google Analytics.",
      information: {
        title: "1. Πληροφορίες που Συλλέγουμε",
        content:
          "Προς το παρόν, δεν συλλέγουμε προσωπικές πληροφορίες απευθείας από τους επισκέπτες του ιστότοπού μας, εκτός από τα δεδομένα που συλλέγονται μέσω του Google Analytics και το email και το μήνυμα που συλλέγονται από τη φόρμα επικοινωνίας.",
      },
      googleAnalytics: {
        title: "2. Χρήση του Google Analytics",
        content:
          "Χρησιμοποιούμε το Google Analytics, μια υπηρεσία ανάλυσης ιστού που παρέχεται από την Google, Inc. Το Google Analytics χρησιμοποιεί cookies για να μας βοηθήσει να κατανοήσουμε πώς οι επισκέπτες αλληλεπιδρούν με τον ιστότοπό μας. Οι πληροφορίες που δημιουργούνται από αυτά τα cookies σχετικά με τη χρήση του ιστότοπου (συμπεριλαμβανομένης της ανωνυμοποιημένης διεύθυνσης IP σας) μεταδίδονται και αποθηκεύονται από την Google σε διακομιστές στις Ηνωμένες Πολιτείες.",
        second:
          "Έχουμε εφαρμόσει την ανωνυμοποίηση IP στο Google Analytics για να διασφαλίσουμε ότι το τελευταίο μέρος της διεύθυνσης IP σας δεν συλλέγεται και αποθηκεύεται.",
      },
      cookies: {
        title: "3. Cookies",
        content:
          "Ο ιστότοπός μας χρησιμοποιεί cookies για να βελτιώσει την εμπειρία σας κατά την πλοήγηση στο περιεχόμενό μας. Τα cookies είναι μικρά αρχεία κειμένου που αποθηκεύονται στη συσκευή σας και μας βοηθούν να κατανοήσουμε πώς αλληλεπιδράτε με τον ιστότοπό μας. Μπορείτε να απενεργοποιήσετε τα cookies στις ρυθμίσεις του προγράμματος περιήγησής σας, αλλά αυτό μπορεί να επηρεάσει την εμπειρία σας στον ιστότοπό μας.",
      },
      dataRetention: {
        title: "4. Διατήρηση Δεδομένων",
        content:
          "Διατηρούμε τα προσωπικά δεδομένα που συλλέγονται μέσω του Google Analytics και της φόρμας επικοινωνίας για περίοδο 26 μηνών. Μετά από αυτή την περίοδο, τα δεδομένα διαγράφονται αυτόματα.",
      },
      rights: {
        title: "5. Τα Δικαιώματά σας",
        content:
          "Έχετε το δικαίωμα πρόσβασης, ενημέρωσης ή διαγραφής των προσωπικών σας δεδομένων που συλλέγονται μέσω του Google Analytics και της φόρμας επικοινωνίας. Εάν επιθυμείτε να ασκήσετε αυτά τα δικαιώματα, παρακαλούμε επικοινωνήστε μαζί μας στο ",
      },
      internationalDataTransfers: {
        title: "6. Διεθνείς Μεταφορές Δεδομένων",
        content:
          "Παρακαλούμε σημειώστε ότι τα δεδομένα που συλλέγονται από το Google Analytics μπορεί να μεταφερθούν σε διακομιστές που βρίσκονται στις Ηνωμένες Πολιτείες, οι οποίες μπορεί να έχουν διαφορετικούς νόμους προστασίας δεδομένων από αυτούς της ΕΕ. Χρησιμοποιώντας τον ιστότοπό μας, συναινείτε στη μεταφορά των δεδομένων σας εκτός της ΕΕ, υπό την προϋπόθεση των διασφαλίσεων που υπάρχουν, όπως η χρήση των Τυποποιημένων Συμβατικών Ρητρών της Google για διεθνείς μεταφορές δεδομένων.",
      },
      thirdPartyServices: {
        title: "7. Υπηρεσίες Τρίτων",
        content:
          "Δεν μοιραζόμαστε προσωπικά δεδομένα με υπηρεσίες τρίτων εκτός από το Google Analytics. Ωστόσο, εάν αποφασίσουμε να συνεργαστούμε με άλλες υπηρεσίες τρίτων στο μέλλον, θα ενημερώσουμε αυτήν την πολιτική απορρήτου αναλόγως.",
      },
      changes: {
        title: "8. Αλλαγές σε Αυτήν την Πολιτική",
        content:
          "Διατηρούμε το δικαίωμα να ενημερώνουμε αυτήν την πολιτική απορρήτου για να αντικατοπτρίζει αλλαγές στις πρακτικές μας ή στις νομικές απαιτήσεις. Σας ενθαρρύνουμε να ανατρέχετε τακτικά σε αυτήν τη σελίδα για τις τελευταίες πληροφορίες σχετικά με τις πρακτικές απορρήτου μας.",
      },
      contact: {
        title: "9. Επικοινωνήστε μαζί μας",
        content:
          "Εάν έχετε οποιεσδήποτε ερωτήσεις σχετικά με αυτήν την πολιτική απορρήτου ή τον τρόπο με τον οποίο χειριζόμαστε τα προσωπικά σας δεδομένα, παρακαλούμε επικοινωνήστε μαζί μας στο:",
      },
    },
    navigation: {
      lang: "Γλώσσα",
      home: "Αρχική",
      services: "Υπηρεσίες",
      contact: "Επικοινωνία",
    },
    hero: {
      title: "NEROM",
      description: "Engineering & Business Services",
    },
    whoWeAre: {
      title: "Ποιοι είμαστε",
      first:
        "Καλώς ήρθατε στη NEROM Engineering Business & Services, την εξειδικευμένη εταιρεία παροχής τεχνικών και συμβουλευτικών υπηρεσιών. Με εμπειρία στους τομείς του μηχανικού, της επιχειρηματικής στρατηγικής και της εκπαίδευσης στελεχών, προσφέρουμε ολοκληρωμένες λύσεις που ανταποκρίνονται στις σύγχρονες απαιτήσεις της αγοράς.",
      second:
        "Από τεχνικές μελέτες και συμβουλευτικές υπηρεσίες μηχανικού έως επιχειρηματική καθοδήγηση και εξειδικευμένη εκπαίδευση, η NEROM συνδυάζει την τεχνογνωσία με την καινοτομία, εξασφαλίζοντας υψηλής ποιότητας υπηρεσίες για την ανάπτυξη και επιτυχία των πελατών της.",
      third:
        "Ανακαλύψτε πώς μπορούμε να σας βοηθήσουμε να πετύχετε τους στόχους σας.",
    },
    expertise: {
      title: "Η εμπειρία μας",
      engineering: {
        title: "Μηχανικοί",
        description:
          "Η NEROM Engineering Business & Services διαθέτει εκτενή εμπειρία στον τομέα του μηχανικού, προσφέροντας εξειδικευμένες υπηρεσίες μελέτης, σχεδιασμού και τεχνικών συμβουλών. Με βαθιά γνώση σε αρχιτεκτονικά, μηχανολογικά, χημικά και έργα λογισμικού, υποστηρίζουμε επιχειρήσεις και επαγγελματίες με καινοτόμες και αποδοτικές λύσεις, διασφαλίζοντας ποιότητα, ακρίβεια και συμμόρφωση με τα υψηλότερα πρότυπα.",
      },
      business: {
        title: "Σύμβουλοι επιχειρήσεων",
        description:
          "Στη NEROM Engineering Business & Services, διαθέτουμε εκτενή εμπειρία στη συμβουλευτική επιχειρήσεων, βοηθώντας εταιρείες να αναπτύξουν αποτελεσματικές στρατηγικές και να βελτιστοποιήσουν τις λειτουργίες τους. Προσφέρουμε εξειδικευμένες υπηρεσίες σε θέματα μάρκετινγκ, προώθησης πωλήσεων και εκπαίδευσης στελεχών, παρέχοντας πρακτικές και καινοτόμες λύσεις που οδηγούν στην ανάπτυξη και την ανταγωνιστικότητα.",
      },
    },
    services: {
      hero: {
        title: "Υπηρεσίες",
        description: "Προσφέρουμε μια μεγάλη γκάμα υπηρεσιών",
      },
      engineering: {
        title: "Υπηρεσίες μηχανικού",
        description:
          "Στη NEROM Engineering Business & Services, προσφέρουμε ένα ευρύ φάσμα υπηρεσιών μηχανικού, παρέχοντας τεχνική εξειδίκευση και καινοτόμες λύσεις για κάθε έργο. Η εμπειρία μας καλύπτει μελέτες, σχεδιασμό και τεχνικές συμβουλές, εξασφαλίζοντας ποιότητα, ακρίβεια και συμμόρφωση με τα υψηλότερα πρότυπα.",
        listTitle: "Οι υπηρεσίες μας περιλαμβάνουν:",
        first:
          "Τεχνικές μελέτες και συμβουλευτικές υπηρεσίες για αρχιτεκτονικά, μηχανολογικά, χημικά και έργα λογισμικού",
        second: "Υποστήριξη έργων από την αρχική σύλληψη έως την υλοποίηση",
        third:
          "Εξειδικευμένες τεχνικές συμβουλές σε θέματα μηχανικής και σχεδιασμού",
        fourth:
          "Ανάπτυξη καινοτόμων λύσεων για βιομηχανικές και τεχνικές εφαρμογές",
        secondListTitle: "Τομείς μηχανικής:",
        secondList: {
          first: "Σχεδιασμός και κατασκευή χώρων μικρής και μεγάλης κλίμακας",
          second: "Σχεδιασμός αντικειμένων",
          third: "Ενεργειακή μηχανική",
          fourth: "Μηχανική χημικών διεργασιών",
          fifth:
            "Λύσεις λογισμικού και σχεδιασμός ιστοσελίδων (όπως η παρούσα)",
        },
        actionLabel: "ΜΑΘΕΤΕ ΠΕΡΙΣΣΟΤΕΡΑ ΓΙΑ ΤΗΝ ΑΡΧΙΤΕΚΤΟΝΙΚΗ",
      },
      business: {
        title: "Συμβουλευτική επιχειρήσεων",
        description:
          "Η NEROM Engineering Business & Services προσφέρει εξειδικευμένες συμβουλευτικές υπηρεσίες, βοηθώντας επιχειρήσεις να βελτιστοποιήσουν τη στρατηγική τους, να ενισχύσουν την ανταγωνιστικότητά τους και να πετύχουν βιώσιμη ανάπτυξη. Μέσα από στοχευμένες λύσεις και πρακτικές συμβουλές, υποστηρίζουμε εταιρείες κάθε μεγέθους να προσαρμοστούν στις σύγχρονες απαιτήσεις της αγοράς.",
        listTitle: "Οι υπηρεσίες μας περιλαμβάνουν:",
        first:
          "Στρατηγικές συμβουλευτικές υπηρεσίες για ανάπτυξη και βελτιστοποίηση επιχειρηματικών διαδικασιών",
        second:
          "Συμβουλές μάρκετινγκ και προώθησης πωλήσεων για αύξηση της αποδοτικότητας και του brand awareness",
        third:
          "Εκπαίδευση και ανάπτυξη στελεχών μέσω εξειδικευμένων σεμιναρίων και επιμορφωτικών προγραμμάτων",
        fourth:
          "Ανάλυση αγοράς και ανταγωνισμού, βοηθώντας τις επιχειρήσεις να λαμβάνουν τεκμηριωμένες αποφάσεις",
        secondListTitle: "Τομείς συμβουλευτικής επιχειρήσεων:",
        secondList: {
          first: "Ανάπτυξη προϊόντων και επιχειρηματικών πλάνων",
          second: "Επιχειρηματική στρατηγική",
          third: "Εκστρατείες μάρκετινγκ",
          fourth: "Εκπαίδευση εμπορικής αποτελεσματικότητας",
        },
      },
      other: {
        title: "Άλλες υπηρεσίες",
        description:
          "Εκτός από τις παραπάνω υπηρεσίες, η NEROM Engineering Business & Services προσφέρει επιπλέον εξειδικευμένες υπηρεσίες που συμπληρώνουν και ενισχύουν το φάσμα των δραστηριοτήτων μας. Στόχος μας είναι η παροχή ολοκληρωμένων λύσεων που καλύπτουν τις ανάγκες των συνεργατών μας με επαγγελματισμό και τεχνογνωσία.",
        listTitle: "Οι υπηρεσίες μας περιλαμβάνουν:",
        first:
          "Εκπαιδευτικά σεμινάρια και επιμορφώσεις, με στόχο την ανάπτυξη δεξιοτήτων και την επαγγελματική κατάρτιση",
        second:
          "Παραγωγή πρωτότυπων ηχογραφήσεων, καλύπτοντας εξειδικευμένες ανάγκες σε ήχο και πολυμέσα",
        third:
          "Εξειδικευμένες επαγγελματικές υπηρεσίες, προσαρμοσμένες στις απαιτήσεις κάθε πελάτη",
      },
    },
    contact: {
      hero: {
        title: "Επικοινωνία",
        description: "Οι ευχαριστημένοι πελάτες στο κέντρο",
      },
      title: "Που θα μας βρείτε",
      content:
        "Επικοινωνήστε μαζί μας για να μάθετε περισσότερα σχετικά με τις υπηρεσίες μας ή για να συζητήσουμε τις ανάγκες της επιχείρησής και του project σας. Μπορείτε να μας καλέσετε, να μας στείλετε email ή να χρησιμοποιήσετε τη φόρμα επικοινωνίας μας.",
      contactDetails: "Στοιχεία επικοινωνίας",
      address: "Ιπποκράτους 188 , Αθήνα ΤΚ 11471",
      contactForm: "Φόρμα επικοινωνίας",
      subject: {
        label: "Θέμα",
        options: {
          general: "Γενική ερώτηση",
          engineering: "Υπηρεσίες μηχανικού",
          business: "Συμβουλευτική επιχειρήσεων",
          other: "Άλλες υπηρεσίες",
        },
        hint: "Παρακαλώ επιλέξτε μια τιμή",
      },
      email: {
        label: "Email",
        hint: "Παρακαλώ εισάγετε μια έγκυρη διεύθυνση email",
      },
      message: {
        label: "Μήνυμα",
        hint: "Επιτρέπονται μόνο γράμματα, αριθμοί, κενά και σημεία στίξης",
      },
      send: "Αποστολη",
      success: {
        title: "Μήνυμα εστάλη",
        content:
          "Σας ευχαριστούμε που επικοινωνήσατε μαζί μας. Θα σας απαντήσουμε το συντομότερο δυνατό.",
        actionButtonLabel: "Επιστροφη στην επικοινωνια",
      },
      error: {
        title: "Σφάλμα",
        content:
          "Παρουσιάστηκε σφάλμα κατά την αποστολή του μηνύματός σας. Παρακαλώ δοκιμάστε ξανά αργότερα.",
        actionButtonLabel: "Επιστροφη στην επικοινωνια",
      },
    },
    architecture: {
      title: "Αρχιτεκτονική",
      description:
        "Οι αρχιτεκτονικές μας υπηρεσίες προσαρμόζονται στις ανάγκες σας",
      back: "Πίσω στην αρχιτεκτονική",
      learnMore: "Μαθετε περισσοτερα",
      projects: {
        filiates: {
          title: "Άνετο Μικρό Σπίτι στους Φιλιάτες",
          description:
            "Ένα άνετο μικρό σπίτι που βρίσκεται στο γραφικό χωριό των Φιλιατών, προσφέροντας μια ήσυχη απόδραση στην καρδιά της φύσης. Το σπίτι διαθέτει παραδοσιακό σχεδιασμό με σύγχρονες ανέσεις, παρέχοντας ένα άνετο και χαλαρωτικό περιβάλλον για τους κατοίκους του.",
          alt1: "Μοντέρνο Μπάνιο",
          alt2: "Ευρύχωρη Κουζίνα",
          alt3: "Κουζίνα με Πλαϊνό Τραπέζι",
        },
        lux_home: {
          title: "Κομψό Πολυτελές Σπίτι",
          description:
            "Ένα κομψό πολυτελές σπίτι σχεδιασμένο για να προσφέρει την απόλυτη άνεση και στυλ. Το σπίτι διαθέτει ευρύχωρα δωμάτια, σύγχρονες ανέσεις και πολυτελείς φινιρίσματα, δημιουργώντας ένα εκλεπτυσμένο και φιλόξενο περιβάλλον για τους κατοίκους του.",
          alt1: "Μοντέρνα Κουζίνα",
          alt2: "Παιδικό Δωμάτιο",
          alt3: "Κύρια Κρεβατοκάμαρα",
          alt4: "Κρεβατοκάμαρα και Δωμάτιο-Ντουλάπα",
          alt5: "Δωμάτιο-Ντουλάπα",
        },
      },
    },
  },
};

export type Lang = "en" | "el";

export function getLocalization(key: string, lang: Lang) {
  const keys = key.split(".");
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let result = content[lang] as any;

  for (const k of keys) {
    if (result[k] === undefined) {
      return null;
    }
    result = result[k];
  }

  return result;
}
